spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres}
    username: ${DB_USERNAME:postgres.qnanpnychsbfuneisikv}
    password: ${DB_PASSWORD}
    hikari:
      connection-init-sql: "SET search_path TO public, extensions"
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 50
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
  flyway:
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
